In [1]:
import os
import sys
from pathlib import Path

library_path = os.path.abspath('../../src')
if library_path not in sys.path:
    sys.path.append(library_path)
library_path = Path(library_path)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import  numpy as np

In [3]:
# load data
DATA_PATH = library_path.parent / "data"
PLOTS_PATH = library_path.parent / "plots"

In [4]:
df = pd.read_csv(
    DATA_PATH / "Data_verysmall_Apr2026.csv", 
    encoding='latin-1',
    low_memory=False
)

In [5]:
df

,ID,Sex,wt_int,eqv3,eqv5,MO5L,SC5L,UA5L,PD5L,AD5L,...,skin,dataset,SurveyWeight,daphnie_surveywt,sat,ill_dis,meds_num,svy_wt,PA_vig,PA_mod
0,NaN,Male,NaN,NaN,NaN,Slight,No Problems,No Problems,No Problems,No Problems,...,NaN,DAPHNIE Pilot 2023,NaN,NaN,NaN,no,3+ meds,1.0,0,0
1,NaN,Male,NaN,NaN,NaN,No Problems,No Problems,No Problems,No Problems,No Problems,...,NaN,DAPHNIE Pilot 2023,NaN,NaN,NaN,no,none,1.0,1,1
2,NaN,Female,NaN,NaN,NaN,No Problems,No Problems,No Problems,No Problems,No Problems,...,NaN,DAPHNIE Pilot 2023,NaN,NaN,NaN,no,2 meds,1.0,3,4
3,NaN,Female,NaN,NaN,NaN,Severe,Slight,Moderate,Moderate,Slight,...,NaN,DAPHNIE Pilot 2023,NaN,NaN,NaN,yes,3+ meds,1.0,0,0
4,NaN,Female,NaN,NaN,NaN,No Problems,No Problems,No Problems,No Problems,No Problems,...,NaN,DAPHNIE Pilot 2023,NaN,NaN,NaN,no,NaN,1.0,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38990,NaN,Female,NaN,NaN,NaN,No Problems,No Problems,No Problems,Slight,Moderate,...,0.0,DAPHNIE 2024,0.92,0.92,NaN,no,1 meds,1.0,NaN,NaN
38991,NaN,Female,NaN,NaN,NaN,No Problems,No Problems,No Problems,No Problems,No Problems,...,0.0,DAPHNIE 2024,0.90,0.90,NaN,no,none,1.0,NaN,NaN
38992,NaN,Male,NaN,NaN,NaN,Moderate,No Problems,Slight,Slight,No Problems,...,0.0,DAPHNIE 2024,0.84,0.84,10.0,no,3+ meds,1.0,NaN,NaN
38993,NaN,Female,NaN,NaN,NaN,No Problems,No Problems,No Problems,No Problems,No Problems,...,0.0,DAPHNIE 2024,1.01,1.01,7.5,yes,2 meds,1.0,NaN,NaN
38994,NaN,Male,NaN,NaN,NaN,No Problems,No Problems,No Problems,No Problems,No Problems,...,0.0,DAPHNIE 2024,1.02,1.02,NaN,no,2 meds,1.0,NaN,NaN

In [6]:
alcohol_pct = (
    df.groupby("dataset")["alcohol_yr"]
    .value_counts(normalize=True, dropna=False)
    .mul(100).round(1)
    .rename("pct")
    .reset_index()
    .pivot(index="alcohol_yr", columns="dataset", values="pct")
    .fillna(0)
)

alcohol_n = pd.crosstab(
    df["alcohol_yr"].fillna("(missing)"),
    df["dataset"],
    margins=True,
    margins_name="Total",
)

# column-wise proportions (% within each dataset)
alcohol_pct = alcohol_n.div(alcohol_n.loc["Total"]).mul(100).round(1)

print("Counts:")
display(alcohol_n)

print("\nColumn % (within each dataset):")
display(alcohol_pct)

Counts:

dataset,DAPHNIE 2024,DAPHNIE Pilot 2023,HSE 2017,HSE 2018,HSE 2019,HSE 2022,Total
alcohol_yr,,,,,,,
(missing),540,124,1366,1371,1498,7727,12626
4+ per wk,484,219,917,984,858,0,3462
monthly or less,1130,350,681,731,704,0,3596
monthly+,889,273,1825,1945,1939,0,6871
never,1305,348,102,107,119,0,1981
weekly+,889,343,3105,3039,3083,0,10459
Total,5237,1657,7996,8177,8201,7727,38995

Column % (within each dataset):

dataset,DAPHNIE 2024,DAPHNIE Pilot 2023,HSE 2017,HSE 2018,HSE 2019,HSE 2022,Total
alcohol_yr,,,,,,,
(missing),10.3,7.5,17.1,16.8,18.3,100.0,32.4
4+ per wk,9.2,13.2,11.5,12.0,10.5,0.0,8.9
monthly or less,21.6,21.1,8.5,8.9,8.6,0.0,9.2
monthly+,17.0,16.5,22.8,23.8,23.6,0.0,17.6
never,24.9,21.0,1.3,1.3,1.5,0.0,5.1
weekly+,17.0,20.7,38.8,37.2,37.6,0.0,26.8
Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0

In [7]:
resp_pct = (
    df.groupby("dataset")["resp"]
    .value_counts(normalize=True, dropna=False)
    .mul(100).round(1)
    .rename("pct")
    .reset_index()
    .pivot(index="resp", columns="dataset", values="pct")
    .fillna(0)
)

resp_n = pd.crosstab(
    df["resp"].fillna("(missing)"),
    df["dataset"],
    margins=True,
    margins_name="Total",
)

# column-wise proportions (% within each dataset)
resp_pct = resp_n.div(resp_n.loc["Total"]).mul(100).round(1)

print("Counts:")
display(resp_n)

print("\nColumn % (within each dataset):")
display(resp_pct)

Counts:

dataset,DAPHNIE 2024,DAPHNIE Pilot 2023,HSE 2017,HSE 2018,HSE 2019,HSE 2022,Total
resp,,,,,,,
0.0,4758,1515,7331,7477,0,7126,28207
1.0,479,142,665,700,0,601,2587
(missing),0,0,0,0,8201,0,8201
Total,5237,1657,7996,8177,8201,7727,38995

Column % (within each dataset):

dataset,DAPHNIE 2024,DAPHNIE Pilot 2023,HSE 2017,HSE 2018,HSE 2019,HSE 2022,Total
resp,,,,,,,
0.0,90.9,91.4,91.7,91.4,0.0,92.2,72.3
1.0,9.1,8.6,8.3,8.6,0.0,7.8,6.6
(missing),0.0,0.0,0.0,0.0,100.0,0.0,21.0
Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0

# Column Exploration

Reference overview of all columns: dtypes, missingness, unique counts, and value distributions.
Used to inform encoding decisions before wrangling.

In [8]:
CATEGORICAL_THRESHOLD = 30  # columns with <= this many unique values get value listings

overview_rows = []
for col in df.columns:
    n_missing = df[col].isna().sum()
    n_unique = df[col].nunique(dropna=True)
    overview_rows.append({
        "column": col,
        "dtype": str(df[col].dtype),
        "missing": n_missing,
        "missing_pct": round(n_missing / len(df) * 100, 1),
        "n_unique": n_unique,
    })

overview = pd.DataFrame(overview_rows).set_index("column")
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns\n")
display(overview)

Shape: 38,995 rows × 48 columns

                    dtype  missing  missing_pct  n_unique
column
ID                float64    30999         79.5      7996
Sex                   str       50          0.1         2
wt_int            float64     6894         17.7     20997
eqv3                  str     6894         17.7         5
eqv5                  str     6894         17.7         7
MO5L                  str    17551         45.0         5
SC5L                  str    17572         45.1         5
UA5L                  str    17569         45.1         5
PD5L                  str    17570         45.1         5
AD5L                  str    17598         45.1         5
EQvas             float64    18138         46.5       101
FULLHEALTH            str    17804         45.7         2
anyprob               str    17804         45.7         2
mo2cat                str    17551         45.0         2
sc2cat                str    17572         45.1         2
ua2cat                str    17569         45.1         2
pd2cat                str    17570         45.1         2
ad2cat                str    17598         45.1         2
LSS_rs            float64    17804         45.7        21
bmi_calc          float64    13414         34.4     23569
bmi_cat               str    13414         34.4         4
edu_cat               str     1879          4.8         4
edu_pst               str    31035         79.6         3
christian_bin         str    11043         28.3         2
EQ_index          float64    17804         45.7       659
emp_cat               str      105          0.3         5
age3cat               str    15071         38.6         3
age7cat           float64       67          0.2         7
eth4cat               str      322          0.8         4
srh                   str      324          0.8         5
paVig                 str     1502          3.9         3
paMod                 str     1324          3.4         4
smoke_ever            str        0          0.0         2
smoke_ecig            str        0          0.0         2
alcohol_yr            str    12626         32.4         5
diabetes            int64        0          0.0         2
obese               int64        0          0.0         2
resp              float64     8201         21.0         2
skin              float64     9858         25.3         2
dataset               str        0          0.0         6
SurveyWeight          str    33758         86.6        11
daphnie_surveywt  float64    34567         88.6        10
sat               float64     9902         25.4        13
ill_dis               str      541          1.4         2
meds_num              str    14041         36.0         4
svy_wt            float64        0          0.0     20980
PA_vig                str    37338         95.8        11
PA_mod                str    37338         95.8         9

In [9]:
# Categorical columns: list all unique values (sorted)
cat_cols = overview[overview["n_unique"] <= CATEGORICAL_THRESHOLD].index.tolist()

print(f"{'='*60}")
print(f"CATEGORICAL COLUMNS ({len(cat_cols)} columns, <= {CATEGORICAL_THRESHOLD} unique values)")
print(f"{'='*60}\n")

for col in cat_cols:
    vals = sorted(df[col].dropna().unique(), key=str)
    missing_pct = overview.loc[col, "missing_pct"]
    print(f"  {col}  [missing: {missing_pct}%]")
    print(f"    {vals}\n")

============================================================
CATEGORICAL COLUMNS (42 columns, <= 30 unique values)
============================================================

  Sex  [missing: 0.1%]
    ['Female', 'Male']

  eqv3  [missing: 17.7%]
    ['Age of household member refused', 'Highest Tertile (>£38,897)', 'Item not applicable', 'Lowest Tertile (<=£19,204)', 'Middle Tertile (>£19,204- £38,897)']

  eqv5  [missing: 17.7%]
    ['Age of household member refused', 'Highest Quintile (>£52,816)', 'Item not applicable', 'Lowest Quintile (<=£14,832)', 'Middle Quintile (>£22,100 <=£32,231 )', 'Second highest Quintile (>£32,231 <=£52,816)', 'Second lowest Quintile (>£14,832<=£22,100)']

  MO5L  [missing: 45.0%]
    ['Extreme/Unable', 'Moderate', 'No Problems', 'Severe', 'Slight']

  SC5L  [missing: 45.1%]
    ['Extreme/Unable', 'Moderate', 'No Problems', 'Severe', 'Slight']

  UA5L  [missing: 45.1%]
    ['Extreme/Unable', 'Moderate', 'No Problems', 'Severe', 'Slight']

  PD5L  [missing: 45.1%]
    ['Extreme/Unable', 'Moderate', 'No Problems', 'Severe', 'Slight']

  AD5L  [missing: 45.1%]
    ['Extreme/Unable', 'Moderate', 'No Problems', 'Severe', 'Slight']

  FULLHEALTH  [missing: 45.7%]
    ['Full Health', 'Has problems']

  anyprob  [missing: 45.7%]
    ['Has Problems', 'No Problems']

  mo2cat  [missing: 45.0%]
    ['Any Problems', 'No Problems']

  sc2cat  [missing: 45.1%]
    ['Any Problems', 'No Problems']

  ua2cat  [missing: 45.1%]
    ['Any Problems', 'No Problems']

  pd2cat  [missing: 45.1%]
    ['Any Problems', 'No Problems']

  ad2cat  [missing: 45.1%]
    ['Any Problems', 'No Problems']

  LSS_rs  [missing: 45.7%]
    [np.float64(0.0), np.float64(10.0), np.float64(100.0), np.float64(15.0), np.float64(20.0), np.float64(25.0), np.float64(30.0), np.float64(35.0), np.float64(40.0), np.float64(45.0), np.float64(5.0), np.float64(50.0), np.float64(55.0), np.float64(60.0), np.float64(65.0), np.float64(70.0), np.float64(75.0), np.float64(80.0), np.float64(85.0), np.float64(90.0), np.float64(95.0)]

  bmi_cat  [missing: 34.4%]
    ['Normal', 'Obese', 'Overweight', 'Underweight']

  edu_cat  [missing: 4.8%]
    ['-9', 'Below degree', 'Degree or equivalent', 'No qualification']

  edu_pst  [missing: 79.6%]
    ['Primary/None', 'Secondary', 'Tertiary']

  christian_bin  [missing: 28.3%]
    ['Christian', 'Non-Christian']

  emp_cat  [missing: 0.3%]
    ['Employed', 'Other (Sick/Home/etc)', 'Retired', 'Student', 'Unemployed']

  age3cat  [missing: 38.6%]
    ['16-34', '35-54', '55+']

  age7cat  [missing: 0.2%]
    [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0)]

  eth4cat  [missing: 0.8%]
    ['Asian', 'Black', 'Others', 'White']

  srh  [missing: 0.8%]
    ['Fair/bad', 'Good/fair', 'Poor/Very bad', 'Very good/Excellent', 'Very good/Good']

  paVig  [missing: 3.9%]
    ['1-2 days', '3+ days', '<2']

  paMod  [missing: 3.4%]
    ['1-2 days', '3-4 days', '5+ days', '<2']

  smoke_ever  [missing: 0.0%]
    ['no', 'yes']

  smoke_ecig  [missing: 0.0%]
    ['no', 'yes']

  alcohol_yr  [missing: 32.4%]
    ['4+ per wk', 'monthly or less', 'monthly+', 'never', 'weekly+']

  diabetes  [missing: 0.0%]
    [np.int64(0), np.int64(1)]

  obese  [missing: 0.0%]
    [np.int64(0), np.int64(1)]

  resp  [missing: 21.0%]
    [np.float64(0.0), np.float64(1.0)]

  skin  [missing: 25.3%]
    [np.float64(0.0), np.float64(1.0)]

  dataset  [missing: 0.0%]
    ['DAPHNIE 2024', 'DAPHNIE Pilot 2023', 'HSE 2017', 'HSE 2018', 'HSE 2019', 'HSE 2022']

  SurveyWeight  [missing: 86.6%]
    [' ', '0.80', '0.84', '0.90', '0.92', '1.00', '1.01', '1.02', '1.14', '1.54', '1.58']

  daphnie_surveywt  [missing: 88.6%]
    [np.float64(0.8), np.float64(0.84), np.float64(0.9), np.float64(0.92), np.float64(1.0), np.float64(1.01), np.float64(1.02), np.float64(1.14), np.float64(1.54), np.float64(1.58)]

  sat  [missing: 25.4%]
    [np.float64(0.0), np.float64(1.0), np.float64(10.0), np.float64(2.0), np.float64(2.5), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(7.5), np.float64(8.0), np.float64(9.0)]

  ill_dis  [missing: 1.4%]
    ['no', 'yes']

  meds_num  [missing: 36.0%]
    ['1 meds', '2 meds', '3+ meds', 'none']

  PA_vig  [missing: 95.8%]
    [' ', '.5', '0', '0.5', '1', '2', '3', '4', '5', '6', '7']

  PA_mod  [missing: 95.8%]
    [' ', '0', '1', '2', '3', '4', '5', '6', '7']

In [10]:
# Continuous columns: summary statistics
cont_cols = overview[overview["n_unique"] > CATEGORICAL_THRESHOLD].index.tolist()

print(f"{'='*60}")
print(f"CONTINUOUS COLUMNS ({len(cont_cols)} columns, > {CATEGORICAL_THRESHOLD} unique values)")
print(f"{'='*60}\n")

if cont_cols:
    display(df[cont_cols].describe().T.round(3))

============================================================
CONTINUOUS COLUMNS (6 columns, > 30 unique values)
============================================================

,count,mean,std,min,25%,50%,75%,max
ID,7996.0,2705989.562,3471.385,2700001.000,2702967.500,2705957.500,2709031.250,2711995.000
wt_int,32101.0,1.000,0.530,0.221,0.752,0.871,1.107,14.115
EQvas,20857.0,75.567,20.217,0.000,68.000,80.000,90.000,100.000
bmi_calc,25581.0,27.489,12.237,0.133,23.624,26.888,30.826,1076.391
EQ_index,21191.0,0.864,0.227,-0.567,0.854,0.944,1.000,1.000
svy_wt,38995.0,1.000,0.481,0.221,0.776,0.937,1.030,14.115

# Variable Encoding and Wrangling

Encoding strategy:
- **Ordinal**: EQ-5D-5L dimensions, income (eqv3/eqv5), education, self-rated health, alcohol frequency, medication count — all have a clear rank order
- **Binary**: Sex, ill_dis, and binary health condition flags
- **Dummy**: ethnicity (eth4cat) and employment status (emp_cat) — nominal categories with no defensible linear order; ordinal encoding would impose false distances in clustering and density ratio estimation

In [12]:
def ordinal_encode(series, mapping, col_name):
    """Map string series to ordinal integers; print any values not covered by the mapping."""
    cleaned = series.str.strip() if series.dtype == object else series
    encoded = cleaned.map(mapping)
    unmapped = cleaned[cleaned.notna() & encoded.isna()].unique()
    if len(unmapped) > 0:
        print(f"  WARNING {col_name}: unmapped values -> {sorted(unmapped, key=str)}")
    return encoded


# Working copy — keeps df intact for reference
df_w = df.copy()

# Drop columns not needed for analysis
df_w = df_w.drop(columns=["ID"])

# Drop rows with invalid age7cat sentinel codes
n_before = len(df_w)
df_w = df_w[~df_w["age7cat"].isin([-1, 0])].copy()
print(f"Dropped {n_before - len(df_w):,} rows with invalid age7cat (-1 or 0).")
print(f"Rows retained: {len(df_w):,}")

# Harmonise dataset label for the DAPHNIE pilot wave
df_w["dataset"] = df_w["dataset"].str.replace("DAPHNIE Pilot 2023", "DAPHNIE 2023", regex=False)
print("\ndataset value counts:")
print(df_w["dataset"].value_counts())

# BMI: values above 70 are physiologically implausible → NaN
n_bmi_outliers = (df_w["bmi_calc"] > 70).sum()
df_w.loc[df_w["bmi_calc"] > 70, "bmi_calc"] = np.nan
print(f"\nReplaced {n_bmi_outliers:,} implausible bmi_calc values (> 70) with NaN.")

Dropped 0 rows with invalid age7cat (-1 or 0).
Rows retained: 38,995

dataset value counts:
dataset
HSE 2019        8201
HSE 2018        8177
HSE 2017        7996
HSE 2022        7727
DAPHNIE 2024    5237
DAPHNIE 2023    1657
Name: count, dtype: int64

Replaced 30 implausible bmi_calc values (> 70) with NaN.

In [13]:
# Drop derived EQ-5D-5L columns — redundant with the 5 encoded dimensions
eq5d_derived = ["FULLHEALTH", "anyprob", "mo2cat", "sc2cat", "ua2cat", "pd2cat", "ad2cat"]

# Drop DAPHNIE-specific columns — present only in DAPHNIE waves, not harmonised across datasets
daphnie_specific = [
    "SAH", "age", "age10", "educ", "inco3", "inco5",
    "empl", "hpempl", "mars", "size", "limc", "scls",
    "urbn", "help", "paVig", "paMod", "daphnie_surveywt",
]

cols_to_drop = [c for c in eq5d_derived + daphnie_specific if c in df_w.columns]
df_w = df_w.drop(columns=cols_to_drop)
n_eq5d_dropped = sum(c in cols_to_drop for c in eq5d_derived)
n_daphnie_dropped = sum(c in cols_to_drop for c in daphnie_specific)

print(
    f"Dropped {len(cols_to_drop)} columns "
    f"({n_eq5d_dropped} EQ-5D-5L derived, {n_daphnie_dropped} DAPHNIE-specific)."
)
print(f"Remaining: {df_w.shape[1]} columns")

Dropped 10 columns (7 EQ-5D-5L derived, 3 DAPHNIE-specific).
Remaining: 37 columns

In [14]:
# EQ-5D-5L dimensions: ordinal 1–5
eq5d_map = {
    "No Problems":       1,
    "Slight":            2,
    "Moderate":          3,
    "Severe":            4,
    "Extreme/Unable":    5,
}
eq5d_dims = ["MO5L", "SC5L", "UA5L", "PD5L", "AD5L"]

print("EQ-5D-5L encoding:")
for col in eq5d_dims:
    df_w[col] = ordinal_encode(df_w[col], eq5d_map, col)
print("  Done.")

EQ-5D-5L encoding:
  Done.

In [15]:
# Income: ordinal lowest→highest
# Stata non-response codes that survived as strings — replace with NaN before mapping
income_na_codes = {"Age of household member refused", "Item not applicable"}
for col in ["eqv3", "eqv5"]:
    df_w[col] = df_w[col].str.strip().replace(income_na_codes, np.nan)
    
eqv3_map = {
    "Lowest Tertile (<=£19,204)":           1,
    "Middle Tertile (>£19,204- £38,897)":   2,
    "Highest Tertile (>£38,897)":           3,
}
eqv5_map = {
    "Lowest Quintile (<=£14,832)":              1,
    "Second lowest Quintile (>£14,832<=£22,100)":        2,
    "Middle Quintile (>£22,100 <=£32,231 )":    3,
    "Second highest Quintile (>£32,231 <=£52,816)":        4,
    "Highest Quintile (>£52,816)":              5,
}

print("Income encoding:")
df_w["eqv3"] = ordinal_encode(df_w["eqv3"], eqv3_map, "eqv3")
df_w["eqv5"] = ordinal_encode(df_w["eqv5"], eqv5_map, "eqv5")
print("  Done.")

Income encoding:
  Done.

In [16]:
# Other ordinal variables

# -9 is a Stata sentinel code in edu_cat — replace before mapping
df_w["edu_cat"] = df_w["edu_cat"].str.strip().replace({"-9": np.nan})

edu_cat_map = {
    "No qualification":      1,
    "Below degree":          2,
    "Degree or equivalent":  3,
    "Higher than degree":    4,
}
edu_pst_map = {
    "Primary/None": 1,
    "Secondary":    2,
    "Tertiary":     3,
}
srh_map = {
    "Poor/Very bad":        1,
    "Fair/bad":             2,
    "Good/fair":            3,
    "Very good/Good":       4,
    "Very good/Excellent":  5,
}
alcohol_map = {
    "never":            0,
    "monthly or less":  1,
    "monthly+":         2,
    "weekly+":          3,
    "4+ per wk":        4,
}
meds_map = {
    "none":     0,
    "1 meds":   1,
    "2 meds":   2,
    "3+ meds":  3,
}
ill_dis_map = {
    "no":  0,
    "yes": 1,
}
bmi_cat_map = {
    "Underweight": 1,
    "Normal":      2,
    "Overweight":  3,
    "Obese":       4,
}
age3cat_map = {
    "16-34": 1,
    "35-54": 2,
    "55+":   3,
}

print("Other ordinal encoding:")
for col, mapping in [
    ("edu_cat",   edu_cat_map),
    ("edu_pst",   edu_pst_map),
    ("srh",       srh_map),
    ("meds_num",  meds_map),
    ("ill_dis",   ill_dis_map),
    ("bmi_cat",   bmi_cat_map),
    ("age3cat",   age3cat_map),
]:
    if col in df_w.columns:
        df_w[col] = ordinal_encode(df_w[col], mapping, col)

# alcohol_yr: normalise case before mapping
if "alcohol_yr" in df_w.columns:
    df_w["alcohol_yr"] = ordinal_encode(
        df_w["alcohol_yr"].str.strip().str.lower(),
        alcohol_map,
        "alcohol_yr",
    )

print("  Done.")

Other ordinal encoding:
  Done.

In [17]:
# Binary encoding
df_w["Sex"] = df_w["Sex"].str.strip().map({"Male": 0, "Female": 1})

for col in ["smoke_ever", "smoke_ecig"]:
    if col in df_w.columns:
        df_w[col] = df_w[col].str.strip().map({"no": 0, "yes": 1})

if "christian_bin" in df_w.columns:
    df_w["christian_bin"] = df_w["christian_bin"].str.strip().map({"Non-Christian": 0, "Christian": 1})

for col in ["obese", "resp", "skin", "diabetes", "bowel", "mus"]:
    if col in df_w.columns:
        df_w[col] = pd.to_numeric(df_w[col], errors="coerce")

print("Binary encoding done.")
print(df_w[["Sex", "smoke_ever", "smoke_ecig", "christian_bin"]].dtypes)

Binary encoding done.
Sex              float64
smoke_ever         int64
smoke_ecig         int64
christian_bin    float64
dtype: object

In [18]:
# Dummy encoding for nominal categoricals
dummy_cols = [c for c in ["eth4cat", "emp_cat"] if c in df_w.columns]

df_w = pd.get_dummies(df_w, columns=dummy_cols, drop_first=False, dtype=float)

new_dummies = [c for c in df_w.columns if any(c.startswith(d + "_") for d in dummy_cols)]
print(f"Dummy columns created ({len(new_dummies)}):")
print(new_dummies)

Dummy columns created (9):
['eth4cat_Asian', 'eth4cat_Black', 'eth4cat_Others', 'eth4cat_White', 'emp_cat_Employed', 'emp_cat_Other (Sick/Home/etc)', 'emp_cat_Retired', 'emp_cat_Student', 'emp_cat_Unemployed']

In [19]:
# Final check
print(f"Final shape: {df_w.shape[0]:,} rows × {df_w.shape[1]} columns")
print(f"\nRemaining object/string columns (may need attention):")
obj_cols = df_w.select_dtypes(include=["object", "string"]).columns.tolist()
for col in obj_cols:
    print(f"  {col}: {sorted(df_w[col].dropna().unique(), key=str)[:10]}")

df_w.to_csv(DATA_PATH / "wrangled_data.csv", index=False)
print("\nSaved to data/wrangled_data.csv")

Final shape: 38,995 rows × 44 columns

Remaining object/string columns (may need attention):
  dataset: ['DAPHNIE 2023', 'DAPHNIE 2024', 'HSE 2017', 'HSE 2018', 'HSE 2019', 'HSE 2022']
  SurveyWeight: [' ', '0.80', '0.84', '0.90', '0.92', '1.00', '1.01', '1.02', '1.14', '1.54']
  PA_vig: [' ', '.5', '0', '0.5', '1', '2', '3', '4', '5', '6']
  PA_mod: [' ', '0', '1', '2', '3', '4', '5', '6', '7']

Saved to data/wrangled_data.csv

In [20]:
df_w.columns

Index(['Sex', 'wt_int', 'eqv3', 'eqv5', 'MO5L', 'SC5L', 'UA5L', 'PD5L', 'AD5L',
       'EQvas', 'LSS_rs', 'bmi_calc', 'bmi_cat', 'edu_cat', 'edu_pst',
       'christian_bin', 'EQ_index', 'age3cat', 'age7cat', 'srh', 'smoke_ever',
       'smoke_ecig', 'alcohol_yr', 'diabetes', 'obese', 'resp', 'skin',
       'dataset', 'SurveyWeight', 'sat', 'ill_dis', 'meds_num', 'svy_wt',
       'PA_vig', 'PA_mod', 'eth4cat_Asian', 'eth4cat_Black', 'eth4cat_Others',
       'eth4cat_White', 'emp_cat_Employed', 'emp_cat_Other (Sick/Home/etc)',
       'emp_cat_Retired', 'emp_cat_Student', 'emp_cat_Unemployed'],
      dtype='str')